inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - "Gemfile"
    - "bin/**/*"
    - "db/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "vendor/**/*"
    - "lib/tasks/auto_annotate_models.rake"
    - "config/environments/*"
    - "config/initializers/*"
    - "config/puma.rb"

Metrics:
  Enabled: false

Layout/LineLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

# Rails関連
Rails/UniqueValidationWithoutIndex:
  Enabled: false

# RSPEC関連
RSpec/ContextWording:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Rails/RootPathnameMethods:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Rails/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
