version: '3'
services:
  mysql:
    image: mysql:8.0.29
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
  solomeal:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/solomeal
    environment:
      SELENIUM_REMOTE_URL: http://webdriver_chrome:4444/wd/hub
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    tty: true
    stdin_open: true
