version: 2.1

jobs:
  build:
    working_directory: ~/solomeal
    docker:
      - image: cimg/ruby:2.7.6
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/solomeal
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: run rspec
          command: docker-compose exec solomeal rspec -fd