version: 2.1

jobs:
  build:
    working_directory: ~/solomeal
    docker:
      - image: cimg/ruby:2.7.6
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/solomeal
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: rails db:migrate
          command: |
            set -x
            docker-compose up -d
            docker exec solomeal curl -4 --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3000
      - run:
          name: Database setup
          command: docker-compose exec solomeal bash -c 'yes n | bundle exec rails g spree:install --migrate --seed --sample --auto_accept'
      - run:
          name: run rspec
          command: docker-compose exec solomeal rspec