version: 2.1
jobs:
  rspec:
    working_directory: ~/solomeal
    docker:
      - image: cimg/ruby:2.7.3
    resource_class: small
    steps:
      - checkout
      # Docker関連コマンドが、この環境で安全に実行できるようにする
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: docker-compose up -d
          command: |
            docker-compose up -d
      - run:
          name: Run rspec
          command: |
            docker-compose exec solomeal rspec
  rubocop:
    working_directory: ~/solomeal
    docker:
      - image: cimg/ruby:2.7.3
    resource_class: small
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

# 実行する順番を記述
workflows:
  version: 2.1
  build:
    jobs:
      - rspec
