version: 2.1

jobs:
  build:
    working_directory: ~/solomeal
    docker:
      - image: cimg/ruby:2.7.6
    steps:
      - checkout:
          path: ~/solomeal
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: set docker
          command: docker-compose build