version: 2.1
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.7.6
    resource_class: small
    working_directory: ~/solomeal
  steps:
    - checkout
        path: ~/solomeal
    - ruby/install-deps
