version: 2.1

jobs:
  build:
    working_directory: ~/solomeal
    docker:
      - image: cimg/ruby:2.7.6
    auth:
      username: mydockerhub-user
      password: $DOCKERHUB_PASSWORD
    steps:
      - checkout:
          path: ~/solomeal
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t CircleCI-Public/circleci-demo-docker:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push CircleCI-Public/circleci-demo-docker:$TAG
      - run:
          name: docker-compose up -d
          command: |
            docker-compose build
            docker-compose up -d
            rspec
      - run:
          name: run rspec
          command: docker-compose exec solomeal rspec -fd